import os

class ProjectArchitect:
    def __init__(self):
        self.templates = {
            "1": ("Web_Scraper", "import requests\nfrom bs4 import BeautifulSoup\n\ndef scrape_data(url):\n    # Basic Scraper Logic\n    pass"),
            "2": ("API_Automation", "import requests\n\ndef call_api(endpoint):\n    # API Automation Logic\n    pass"),
            "3": ("Data_Analyzer", "import pandas as pd\n\ndef analyze_data(file):\n    # Data Analysis Logic\n    pass")
        }

    def create_project(self):
        print("\n--- JARVIS AUTO-PROJECT ARCHITECT ---")
        print("Select Sector to Generate Code:")
        print("1. Web Scraper (Market Research)")
        print("2. API Automation (System Integration)")
        print("3. Data Analyzer (Income Analysis)")
        
        choice = input("\nEnter choice (1-3): ")
        
        if choice in self.templates:
            name, code = self.templates[choice]
            filename = f"{name.lower()}_module.py"
            with open(filename, "w") as f:
                f.write(f"# Auto-Generated by Optimus Jarvis Super-Frame\n# Sector: {name}\n\n{code}")
            print(f"\n[SUCCESS] Project '{name}' created as '{filename}'!")
        else:
            print("[ERROR] Invalid selection.")

if __name__ == "__main__":
    architect = ProjectArchitect()
    architect.create_project()
