github.com:
    users:
        deepak-lodha87:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: deepak-lodha87
